ALTER TABLE _person
ADD COLUMN feed_uuid VARCHAR(64) DEFAULT NULL;

DROP VIEW person;

CREATE VIEW `person` AS select p.* from `_person` `p` where ((`getCurrentUserID`() is not null) and ((`p`.`id` = `getCurrentUserID`()) or (`getCurrentUserID`() = -(1)) or (((not(exists(select 1 AS `Not_used` from `account_congregation_restriction` `cr` where (`cr`.`personid` = `getCurrentUserID`())))) or `p`.`congregationid` in (select `cr`.`congregationid` AS `congregationid` from `account_congregation_restriction` `cr` where (`cr`.`personid` = `getCurrentUserID`()))) and ((not(exists(select 1 AS `Not_used` from `account_group_restriction` `gr` where (`gr`.`personid` = `getCurrentUserID`())))) or `p`.`id` in (select `m`.`personid` AS `personid` from (`person_group_membership` `m` join `account_group_restriction` `gr` on((`m`.`groupid` = `gr`.`groupid`))) where (`gr`.`personid` = `getCurrentUserID`()))))));

DROP VIEW member;

CREATE VIEW `member` AS select `mp`.`id` AS `id`,`mp`.`first_name` AS `first_name`,`mp`.`last_name` AS `last_name`,`mp`.`gender` AS `gender`,`mp`.`age_bracket` AS `age_bracket`,`mp`.`congregationid` AS `congregationid`,`mp`.`email` AS `email`,`mp`.`mobile_tel` AS `mobile_tel`,`mp`.`work_tel` AS `work_tel`,`mp`.`familyid` AS `familyid`,`mf`.`family_name` AS `family_name`,`mf`.`address_street` AS `address_street`,`mf`.`address_suburb` AS `address_suburb`,`mf`.`address_state` AS `address_state`,`mf`.`address_postcode` AS `address_postcode`,`mf`.`home_tel` AS `home_tel`, mp.feed_uuid from (((((`_person` `mp` join `family` `mf` on((`mf`.`id` = `mp`.`familyid`))) join `person_group_membership` `pgm1` on((`pgm1`.`personid` = `mp`.`id`))) join `_person_group` `pg` on(((`pg`.`id` = `pgm1`.`groupid`) and (`pg`.`share_member_details` = 1)))) join `person_group_membership` `pgm2` on((`pgm2`.`groupid` = `pg`.`id`))) join `_person` `up` on((`up`.`id` = `pgm2`.`personid`))) where ((`up`.`id` = `getCurrentUserID`()) and (`mp`.`status` <> 'archived') and (`mf`.`status` <> 'archived') and (`up`.`status` <> 'archived')) union select `mp`.`id` AS `id`,`mp`.`first_name` AS `first_name`,`mp`.`last_name` AS `last_name`,`mp`.`gender` AS `gender`,`mp`.`age_bracket` AS `age_bracket`,`mp`.`congregationid` AS `congregationid`,`mp`.`email` AS `email`,`mp`.`mobile_tel` AS `mobile_tel`,`mp`.`work_tel` AS `work_tel`,`mp`.`familyid` AS `familyid`,`mf`.`family_name` AS `family_name`,`mf`.`address_street` AS `address_street`,`mf`.`address_suburb` AS `address_suburb`,`mf`.`address_state` AS `address_state`,`mf`.`address_postcode` AS `address_postcode`,`mf`.`home_tel` AS `home_tel` from ((`_person` `mp` join `family` `mf` on((`mf`.`id` = `mp`.`familyid`))) join `_person` `self` on((`self`.`familyid` = `mp`.`familyid`))) where ((`self`.`id` = `getCurrentUserID`()) and (`mp`.`status` <> 'archived') and (`mf`.`status` <> 'archived') and ((`self`.`status` <> 'archived') or (`mp`.`id` = `self`.`id`)));

