INSERT INTO `service_component` (`categoryid`, `title`, `alt_title`, `length_mins`, `is_numbered`, `runsheet_title_format`, `handout_title_format`, `show_in_handout`, `show_on_slide`, `content_html`, `credits`, `ccli_number`) VALUES
(2, 'Confession BG5.1', '', 2, '1', '', 'Confession of Sins', '1', '', '<div>\r\n	Almighty and most merciful Father,</div>\r\n<div>\r\n	we have erred and strayed from your ways like lost sheep.</div>\r\n<div>\r\n	We have followed too much the devices and desires of our own hearts.</div>\r\n<div>\r\n	We have offended against your holy laws.</div>\r\n<div>\r\n	We have left undone what we ought to have done,</div>\r\n<div>\r\n	and we have done what we ought not to have done,</div>\r\n<div>\r\n	and there is no health in us.</div>\r\n<div>\r\n	Yet, good Lord, have mercy on us:</div>\r\n<div>\r\n	restore those who are penitent,</div>\r\n<div>\r\n	according to your promises declared to us in Jesus Christ our Lord.</div>\r\n<div>\r\n	And grant, merciful Father, for his sake,</div>\r\n<div>\r\n	That we may live a godly, righteous, and obedient life,</div>\r\n<div>\r\n	to the glory of your holy name. Amen.&nbsp;</div>\r\n', '', 0),
(2, 'Confession BG5.2', '', 3, '1', '', 'Confession of Sins', '1', '', '<div>\r\n	Most merciful God,</div>\r\n<div>\r\n	we humbly admit that we need your help.</div>\r\n<div>\r\n	We confess that we have wandered from your way:</div>\r\n<div>\r\n	we have done wrong, and we have failed to do what is right.</div>\r\n<div>\r\n	You alone can save us.</div>\r\n<div>\r\n	Have mercy on us:</div>\r\n<div>\r\n	wipe out our sins and teach us to forgive others.</div>\r\n<div>\r\n	Bring forth in us the fruit of the Spirit</div>\r\n<div>\r\n	that we may live as disciples of Christ.</div>\r\n<div>\r\n	This we ask in the name of Jesus our Saviour. Amen.&nbsp;</div>\r\n', '', 0),
(2, 'Confession BG5.3', '', 3, '1', '', 'Confession of Sins', '1', '', '<div>\r\n	Almighty God, Father of our Lord Jesus Christ,</div>\r\n<div>\r\n	maker of all things, judge of all people,</div>\r\n<div>\r\n	we acknowledge with shame the sins we have committed,</div>\r\n<div>\r\n	by thought, word and deed, against your divine majesty,</div>\r\n<div>\r\n	provoking most justly your wrath and indignation against us.</div>\r\n<div>\r\n	We earnestly repent, and are heartily sorry for all our misdoings.</div>\r\n<div>\r\n	Have mercy on us, most merciful Father.</div>\r\n<div>\r\n	For your Son our Lord Jesus Christ&#39;s sake</div>\r\n<div>\r\n	forgive us all that is past,</div>\r\n<div>\r\n	and grant that from this time forward</div>\r\n<div>\r\n	we may serve and please you in newness of life,</div>\r\n<div>\r\n	to the honour and glory of your name,</div>\r\n<div>\r\n	through Jesus Christ our Lord. Amen.</div>\r\n', '', 0),
(2, 'Confession BG5.4', '', 2, '1', '', 'Confession of Sins', '1', '', '<div>\r\n	Merciful God,</div>\r\n<div>\r\n	our maker and our judge,</div>\r\n<div>\r\n	we have sinned against you in thought, word, and deed:</div>\r\n<div>\r\n	we have not loved you with our whole heart,</div>\r\n<div>\r\n	we have not loved our neighbours as ourselves:</div>\r\n<div>\r\n	we repent, and are sorry for all our sins.</div>\r\n<div>\r\n	Father, forgive us.</div>\r\n<div>\r\n	Strengthen us to love and obey you in newness of life;</div>\r\n<div>\r\n	through Jesus Christ our Lord. Amen.</div>\r\n', '', 0),
(2, 'Confession BG5.5', '', 2, '1', '', 'Confession of Sins', '1', '', '<div>\r\n	Heavenly Father,</div>\r\n<div>\r\n	we praise you for adopting us as your children</div>\r\n<div>\r\n	and making us heirs of eternal life.</div>\r\n<div>\r\n	In your mercy you have washed us from our sins</div>\r\n<div>\r\n	and made us clean in your sight.</div>\r\n<div>\r\n	Yet we still fail to love you as we should</div>\r\n<div>\r\n	and serve you as we ought.</div>\r\n<div>\r\n	Forgive us our sins and renew us by your grace,</div>\r\n<div>\r\n	that we may continue to grow as members of Christ,</div>\r\n<div>\r\n	in whom alone is our salvation. Amen.</div>\r\n', '', 0),
(4, 'Sermon', '', 25, '1', 'Sermon: %NAME_OF_PREACHER%', 'Sermon: "%SERVICE_TOPIC_TITLE%" (%SERVICE_BIBLE_PREACH_ALL%) - %NAME_OF_PREACHER%', '1', '', '', '', 0),
(3, 'Apostles'' Creed', 'Normal version', 2, '1', '', '', '1', '', '<div>\r\n	I believe in God, the Father Almighty,</div>\r\n<div>\r\n	creator of heaven and earth.</div>\r\n<div>\r\n	I believe in Jesus Christ,</div>\r\n<div>\r\n	God&#39;s only Son, our Lord,</div>\r\n<div>\r\n	who was conceived by the Holy Spirit,</div>\r\n<div>\r\n	born of the Virgin Mary,</div>\r\n<div>\r\n	suffered under Pontius Pilate,</div>\r\n<div>\r\n	was crucified, died, and was buried;</div>\r\n<div>\r\n	he descended to the dead.</div>\r\n<div>\r\n	On the third day he rose from the dead;</div>\r\n<div>\r\n	he ascended into heaven,</div>\r\n<div>\r\n	and is seated at the right hand of the Father;</div>\r\n<div>\r\n	from there he will come to judge</div>\r\n<div>\r\n	the living and the dead.</div>\r\n<div>\r\n	I believe in the Holy Spirit,</div>\r\n<div>\r\n	the holy universal Church,</div>\r\n<div>\r\n	the communion of saints,</div>\r\n<div>\r\n	the forgiveness of sins,</div>\r\n<div>\r\n	the resurrection of the body,</div>\r\n<div>\r\n	and the life everlasting. Amen.&nbsp;</div>\r\n', '', 0),
(3, 'Nicene Creed', '', 2, '1', '', '', '1', '', '<div>\r\n	We believe in one God,</div>\r\n<div>\r\n	the Father, the Almighty,</div>\r\n<div>\r\n	maker of heaven and earth</div>\r\n<div>\r\n	of all that is, seen and unseen.</div>\r\n<div>\r\n	We believe in one Lord, Jesus Christ,</div>\r\n<div>\r\n	the only Son of God,</div>\r\n<div>\r\n	eternally begotten of the Father,</div>\r\n<div>\r\n	God from God, Light from Light,</div>\r\n<div>\r\n	true God from true God,</div>\r\n<div>\r\n	begotten not made,</div>\r\n<div>\r\n	of one being with the Father;</div>\r\n<div>\r\n	through him all things were made.</div>\r\n<div>\r\n	For us and for our salvation</div>\r\n<div>\r\n	he came down from heaven,</div>\r\n<div>\r\n	was incarnate of the Holy Spirit and the Virgin Mary</div>\r\n<div>\r\n	and became truly human.</div>\r\n<div>\r\n	For our sake he was crucified under Pontius Pilate;</div>\r\n<div>\r\n	he suffered death and was buried.</div>\r\n<div>\r\n	On the third day he rose again</div>\r\n<div>\r\n	in accordance with the Scriptures;</div>\r\n<div>\r\n	he ascended into heaven</div>\r\n<div>\r\n	and is seated at the right hand of the Father.</div>\r\n<div>\r\n	He will come again in glory to judge</div>\r\n<div>\r\n	the living and the dead</div>\r\n<div>\r\n	and his kingdom will have no end.</div>\r\n<div>\r\n	We believe in the Holy Spirit,</div>\r\n<div>\r\n	the Lord, the giver of life,</div>\r\n<div>\r\n	who proceeds from the Father and the Son,</div>\r\n<div>\r\n	who with the Father and the Son</div>\r\n<div>\r\n	is worshipped and glorified,</div>\r\n<div>\r\n	who has spoken through the prophets.</div>\r\n<div>\r\n	We believe in one holy universal and apostolic Church.</div>\r\n<div>\r\n	We acknowledge one baptism for the forgiveness of sins.</div>\r\n<div>\r\n	We look for the resurrection of the dead,</div>\r\n<div>\r\n	and the life of the world to come. Amen.</div>\r\n', '', 0),
(3, 'Apostles'' Creed', 'Responsive version', 2, '1', '', '', '1', '', '<div>\r\n	Do you believe and trust in God the Father?</div>\r\n<div>\r\n	<strong>We believe in God, the Father Almighty,</strong></div>\r\n<div>\r\n	<strong>creator of heaven and earth.</strong></div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Do you believe and trust in God the Son?</div>\r\n<div>\r\n	<strong>We believe in Jesus Christ,</strong></div>\r\n<div>\r\n	<strong>God&#39;s only Son, our Lord,</strong></div>\r\n<div>\r\n	<strong>who was conceived by the Holy Spirit,</strong></div>\r\n<div>\r\n	<strong>born of the Virgin Mary,</strong></div>\r\n<div>\r\n	<strong>suffered under Pontius Pilate,</strong></div>\r\n<div>\r\n	<strong>was crucified, died and was buried;</strong></div>\r\n<div>\r\n	<strong>he descended to the dead.</strong></div>\r\n<div>\r\n	<strong>On the third day he rose from the dead;</strong></div>\r\n<div>\r\n	<strong>he ascended into heaven.</strong></div>\r\n<div>\r\n	<strong>and is seated at the right hand of the Father;</strong></div>\r\n<div>\r\n	<strong>from there he will come again to</strong></div>\r\n<div>\r\n	<strong>judge the living and the dead.</strong></div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Do you believe and trust in the Holy Spirit?</div>\r\n<div>\r\n	<strong>We believe in the Holy Spirit,</strong></div>\r\n<div>\r\n	<strong>the holy, universal Church,</strong></div>\r\n<div>\r\n	<strong>the fellowship of the saints,</strong></div>\r\n<div>\r\n	<strong>the forgiveness of sins,</strong></div>\r\n<div>\r\n	<strong>the resurrection of the body, and life eternal. Amen.</strong></div>\r\n', '', 0),
(4, 'Bible Readings', '', 3, '1', 'Bible Readings: %SERVICE_BIBLE_READ_ALL%', '', '1', '', '', '', 0),
(4, 'Welcome', '', 1, '1', '', '', '1', '', '', '', 0),
(4, 'Sending out', '', 1, '1', '', '', '1', '', '', '', 0),
(4, 'Announcements', '', 5, '1', '', '', '1', '', '', '', 0),
(4, 'Declaration of God''s forgiveness', '', 1, '1', '', '', '1', '', '', '', 0),
(2, 'Prayers for the church and the world', '', 5, '1', '', '', '1', '', '', '', 0),
(4, 'The Lord''s Supper', '', 1, '1', '', '', '1', '', '', '', 0),
(2, 'Thanksgiving BG11.1', 'We give you humble and hearty thanks...', 2, '1', '', 'Prayer of Thanksgiving', '1', '', '<div>\r\n	Almighty God and merciful Father,</div>\r\n<div>\r\n	we give you humble and hearty thanks</div>\r\n<div>\r\n	for all your goodness and loving kindness</div>\r\n<div>\r\n	to us and to all people.</div>\r\n<div>\r\n	We praise you for creating and sustaining us</div>\r\n<div>\r\n	and for all the blessings of this life;</div>\r\n<div>\r\n	but above all for your amazing love</div>\r\n<div>\r\n	in redeeming the world by our Lord Jesus Christ,</div>\r\n<div>\r\n	giving us grace and the hope of glory.</div>\r\n<div>\r\n	Give us such a sense of all you goodness,</div>\r\n<div>\r\n	that we may be truly thankful, and may praise you</div>\r\n<div>\r\n	not only with our lips, but in our lives,</div>\r\n<div>\r\n	by serving you in holy and righteous ways;</div>\r\n<div>\r\n	through Jesus Christ our Lord,</div>\r\n<div>\r\n	to whom with you and the Holy Spirit,</div>\r\n<div>\r\n	be all honour and glory, now and for ever. Amen.</div>\r\n', '', 0),
(2, 'Thanksgiving BG11.2', 'We humbly thank you for all your gifts...', 1, '1', '', 'Prayer of Thanksgiving', '1', '', '<div>\r\n	Gracious God, our heavenly Father,</div>\r\n<div>\r\n	we humbly thank you</div>\r\n<div>\r\n	for all your gifts so freely given:</div>\r\n<div>\r\n	for life and health and safety,</div>\r\n<div>\r\n	for work and rest and friendship,</div>\r\n<div>\r\n	and for the wonder of creation.</div>\r\n<div>\r\n	We thank you for preserving throughout history</div>\r\n<div>\r\n	a people for yourself.</div>\r\n<div>\r\n	Above all, we praise you for our Saviour Jesus Christ,</div>\r\n<div>\r\n	for his death and resurrection,</div>\r\n<div>\r\n	for your life-giving Spirit,</div>\r\n<div>\r\n	and the hope of sharing in your glory.</div>\r\n<div>\r\n	Fill our hearts with all joy and peace in believing;</div>\r\n<div>\r\n	through Jesus Christ our Lord. Amen.</div>\r\n', '', 0),
(2, 'Thanksgiving BG11.3', 'We praise you for the beauty of the world around us...', 1, '1', '', 'Prayer of Thanksgiving', '1', '', '<div>\r\n	Almighty God, creator and redeemer,</div>\r\n<div>\r\n	we praise you for the beauty of the world around us,</div>\r\n<div>\r\n	and for every gift we enjoy.</div>\r\n<div>\r\n	Thank you for creating us</div>\r\n<div>\r\n	to know you, to love you and to obey you.</div>\r\n<div>\r\n	Most of all we praise you</div>\r\n<div>\r\n	for your amazing love</div>\r\n<div>\r\n	in sending your Son,</div>\r\n<div>\r\n	to restore your world,</div>\r\n<div>\r\n	by dying for us</div>\r\n<div>\r\n	and rising to give us new life.</div>\r\n<div>\r\n	Accept our praise and thanksgiving,</div>\r\n<div>\r\n	through Jesus Christ our Lord. Amen.</div>\r\n', '', 0),
(2, 'Thanksgiving BG11.4', 'You made us in your image to enjoy and govern them...', 1, '1', '', 'Prayer of Thanksgiving', '1', '', '<div>\r\n	Lord, you made all things,</div>\r\n<div>\r\n	and you made us in your image</div>\r\n<div>\r\n	to enjoy and govern them.</div>\r\n<div>\r\n	We thank you</div>\r\n<div>\r\n	for your work of creation,</div>\r\n<div>\r\n	for the beauty we enjoy,</div>\r\n<div>\r\n	for human skill and artistry.</div>\r\n<div>\r\n	We thank you</div>\r\n<div>\r\n	for community, friendship and love,</div>\r\n<div>\r\n	for family and marriage,</div>\r\n<div>\r\n	for the privilege of parenthood.</div>\r\n<div>\r\n	Above all we thank you</div>\r\n<div>\r\n	for Jesus, your Son,</div>\r\n<div>\r\n	through whom you created all things,</div>\r\n<div>\r\n	and by whom you sustain them.</div>\r\n<div>\r\n	We thank you</div>\r\n<div>\r\n	that he became one of us and died</div>\r\n<div>\r\n	to reconcile all creation to you,</div>\r\n<div>\r\n	in heaven and on earth,</div>\r\n<div>\r\n	and to call us into peace with you. Amen.</div>\r\n', '', 0),
(2, 'Lord''s Prayer', '', 2, '1', '', 'The Lord''s Prayer', '1', '', '<div>\r\n	Our Father in heaven,</div>\r\n<div>\r\n	hallowed be your name,</div>\r\n<div>\r\n	your kingdom come,</div>\r\n<div>\r\n	your will be done, on earth as in heaven.</div>\r\n<div>\r\n	Give us today our daily bread.</div>\r\n<div>\r\n	Forgive us our sins</div>\r\n<div>\r\n	as we forgive those who sin against us</div>\r\n<div>\r\n	Lead us not into temptation,</div>\r\n<div>\r\n	but deliver us from evil.</div>\r\n<div>\r\n	For the kingdom, the power, and the glory are yours</div>\r\n<div>\r\n	now and forever. Amen.</div>\r\n', '', 0),
(1, 'Immortal, Invisible, God Only Wise', 'St Denio', 3, '1', '', '', '1', '', '', '', 0),
(1, 'Be Thou My Vision', 'Slane', 3, '1', '', '', '1', '', '', '', 0),
(1, 'Amazing Grace', '', 3, '1', '', '', '1', '', '', '', 0);

insert into congregation_service_component (congregationid, componentid)
select g.id, p.id
from congregation g, service_component p 
where g.meeting_time <> '';